### ISSUE TITLE
[Discussion] : Define roadmap for contenta angular features

### ISSUE THREAD

**Issue by joaogarin** [contentacms/contenta_angular#24]
Lets discuss and define here the roadmap for contenta angular2 features. 

- [ ]  Angular2-jsonapi integration
- [ ]  Build homepage according to [wireframes](https://www.drupal.org/node/2818741#comment-12114776)
- [ ]  Improve service worker
